import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "app-language";

const TRANSLATIONS = {
  en: {
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.addProduct": "Add Product",
    "nav.cart": "Cart",
    "nav.orders": "Orders",
    "nav.admin": "Admin",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.language": "Language",
    "nav.toggleMenu": "Toggle menu",

    "home.kicker": "Agriculture Marketplace",
    "home.headline": "Buy fresh produce, seeds, and agri supplies directly from farmers.",
    "home.description": "Built for transparent farm-to-market trade with trusted local sellers and efficient order management.",
    "home.explore": "Explore Marketplace",
    "home.becomeSeller": "Become a Seller",
    "home.categories": "Categories",
    "home.featured": "Featured Products",
    "home.viewAll": "View all",
    "home.noFeatured": "No featured products available yet.",
    "home.loadingFeatured": "Fetching featured products...",

    "products.marketplace": "Marketplace",
    "products.category": "Category",
    "products.location": "Location",
    "products.organic": "Organic",
    "products.minPrice": "Min Price",
    "products.maxPrice": "Max Price",
    "products.all": "All",
    "products.searchLocation": "Search location",
    "products.nonOrganic": "Non-organic",
    "products.title": "Products",
    "products.items": "{count} items",
    "products.loading": "Loading products...",
    "products.empty": "No products found for selected filters.",

    "auth.loginTitle": "Login",
    "auth.loginSubtitle": "Access your cart, orders, and purchase history.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signingIn": "Signing in...",
    "auth.newHere": "New here?",
    "auth.createAccount": "Create an account",
    "auth.registerTitle": "Create Account",
    "auth.registerSubtitle": "Register as customer, farmer, or vendor.",
    "auth.name": "Name",
    "auth.role": "Role",
    "auth.customer": "Customer",
    "auth.farmer": "Farmer",
    "auth.vendor": "Vendor",
    "auth.creating": "Creating account...",
    "auth.register": "Register",
    "auth.already": "Already have an account?",

    "product.organic": "Organic",
    "product.organicProduct": "Organic Product",
    "product.retail": "Retail",
    "product.wholesale": "Wholesale",
    "product.addToCart": "Add to Cart",
    "product.imageOf": "Image {current} of {total}",
    "product.subcategory": "Subcategory",
    "product.minWholesale": "Minimum wholesale qty",
    "product.location": "Location",
    "product.availableQty": "Available quantity",
    "product.sellerDetails": "Seller Details",
    "product.notFound": "Product not found.",
    "product.loading": "Loading product...",

    "common.na": "N/A",

    "cart.loading": "Loading cart...",
    "cart.title": "My Cart",
    "cart.items": "{count} items",
    "cart.empty": "Your cart is empty.",
    "cart.remove": "Remove",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.processing": "Processing...",

    "orders.loading": "Loading orders...",
    "orders.title": "My Orders",
    "orders.count": "{count} orders",
    "orders.none": "No orders found yet.",
    "orders.placed": "Placed",
    "orders.total": "Total",
    "orders.order": "Order",

    "add.title": "Add Product",
    "add.productName": "Product Name",
    "add.category": "Category",
    "add.subcategory": "Subcategory",
    "add.location": "Location",
    "add.type": "Type",
    "add.organic": "Organic",
    "add.nonOrganic": "Non-organic",
    "add.generateAi": "Generate AI Description",
    "add.generatingAi": "Generating AI content...",
    "add.description": "Description",
    "add.benefits": "Benefits (auto-filled by AI)",
    "add.tags": "Tags (comma separated)",
    "add.retail": "Retail Price",
    "add.wholesale": "Wholesale Price",
    "add.minWholesale": "Min Wholesale Quantity",
    "add.available": "Available Quantity",
    "add.upload": "Upload Product Images",
    "add.uploadHint": "Optional, up to 8 images (max 5MB each).",
    "add.noImage": "No image selected yet.",
    "add.saving": "Saving Product...",
    "add.create": "Create Product",

    "footer.description": "Fresh produce and agri supplies from trusted local sellers across Sri Lanka.",
    "footer.marketplace": "Marketplace",
    "footer.sell": "Sell Products",
    "footer.orders": "Orders",
    "footer.cart": "Cart",
    "footer.bottom": "Built for better farm-to-market trade.",
  },
  si: {
    "nav.home": "මුල් පිටුව",
    "nav.products": "නිෂ්පාදන",
    "nav.addProduct": "නිෂ්පාදනය එක් කරන්න",
    "nav.cart": "කරත්තය",
    "nav.orders": "ඇණවුම්",
    "nav.admin": "පරිපාලක",
    "nav.logout": "ඉවත් වන්න",
    "nav.login": "පිවිසුම",
    "nav.register": "ලියාපදිංචිය",
    "nav.language": "භාෂාව",
    "nav.toggleMenu": "මෙනුව විවෘත/වසා දමන්න",

    "home.kicker": "කෘෂි වෙළඳපොළ",
    "home.headline": "නැවුම් අස්වැන්න, බීජ සහ කෘෂි සැපයුම් ගොවීන්ගෙන්ම මිලදී ගන්න.",
    "home.description": "විශ්වාසදායී වෙළෙන්දන් සමඟ පැහැදිලි ගොවිපල-වෙළඳපොළ වෙළඳාම සඳහා නිර්මාණය කර ඇත.",
    "home.explore": "වෙළඳපොළ බලන්න",
    "home.becomeSeller": "විකුණන්නා වන්න",
    "home.categories": "කාණ්ඩ",
    "home.featured": "ප්‍රධාන නිෂ්පාදන",
    "home.viewAll": "සියල්ල බලන්න",
    "home.noFeatured": "තවම ප්‍රධාන නිෂ්පාදන නොමැත.",
    "home.loadingFeatured": "ප්‍රධාන නිෂ්පාදන පූරණය වෙමින්...",

    "products.marketplace": "වෙළඳපොළ",
    "products.category": "කාණ්ඩය",
    "products.location": "ස්ථානය",
    "products.organic": "සෛව",
    "products.minPrice": "අවම මිල",
    "products.maxPrice": "උපරිම මිල",
    "products.all": "සියල්ල",
    "products.searchLocation": "ස්ථානය සොයන්න",
    "products.nonOrganic": "අසෛව",
    "products.title": "නිෂ්පාදන",
    "products.items": "අයිතම {count}",
    "products.loading": "නිෂ්පාදන පූරණය වෙමින්...",
    "products.empty": "තෝරාගත් පෙරහන් සඳහා නිෂ්පාදන නැත.",

    "auth.loginTitle": "පිවිසුම",
    "auth.loginSubtitle": "ඔබගේ කරත්තය සහ ඇණවුම් වෙත ප්‍රවේශ වන්න.",
    "auth.email": "ඊමේල්",
    "auth.password": "මුරපදය",
    "auth.signingIn": "පිවිසෙමින්...",
    "auth.newHere": "අලුත්ද?",
    "auth.createAccount": "ගිණුමක් සාදන්න",
    "auth.registerTitle": "ගිණුම සාදන්න",
    "auth.registerSubtitle": "පාරිභෝගික, ගොවි හෝ වෙළෙන්දා ලෙස ලියාපදිංචි වන්න.",
    "auth.name": "නම",
    "auth.role": "භූමිකාව",
    "auth.customer": "පාරිභෝගික",
    "auth.farmer": "ගොවි",
    "auth.vendor": "වෙළෙන්දා",
    "auth.creating": "ගිණුම සාදමින්...",
    "auth.register": "ලියාපදිංචි වන්න",
    "auth.already": "දැනටමත් ගිණුමක් තිබේද?",

    "product.organic": "සෛව",
    "product.organicProduct": "සෛව නිෂ්පාදනය",
    "product.retail": "සිල්ලර",
    "product.wholesale": "තොග",
    "product.addToCart": "කරත්තයට එක් කරන්න",
    "product.imageOf": "රූපය {current} / {total}",
    "product.subcategory": "උප කාණ්ඩය",
    "product.minWholesale": "අවම තොග ප්‍රමාණය",
    "product.location": "ස්ථානය",
    "product.availableQty": "ලබා ගත හැකි ප්‍රමාණය",
    "product.sellerDetails": "විකුණන්නාගේ තොරතුරු",
    "product.notFound": "නිෂ්පාදනය හමු නොවීය.",
    "product.loading": "නිෂ්පාදනය පූරණය වෙමින්...",

    "common.na": "නැත",

    "cart.loading": "කරත්තය පූරණය වෙමින්...",
    "cart.title": "මගේ කරත්තය",
    "cart.items": "අයිතම {count}",
    "cart.empty": "ඔබගේ කරත්තය හිස්ය.",
    "cart.remove": "ඉවත් කරන්න",
    "cart.total": "එකතුව",
    "cart.checkout": "ගෙවීමට යන්න",
    "cart.processing": "සැකසෙමින්...",

    "orders.loading": "ඇණවුම් පූරණය වෙමින්...",
    "orders.title": "මගේ ඇණවුම්",
    "orders.count": "ඇණවුම් {count}",
    "orders.none": "තවම ඇණවුම් නොමැත.",
    "orders.placed": "තැබූ දිනය",
    "orders.total": "එකතුව",
    "orders.order": "ඇණවුම",

    "add.title": "නිෂ්පාදනය එක් කරන්න",
    "add.productName": "නිෂ්පාදන නම",
    "add.category": "කාණ්ඩය",
    "add.subcategory": "උප කාණ්ඩය",
    "add.location": "ස්ථානය",
    "add.type": "වර්ගය",
    "add.organic": "සෛව",
    "add.nonOrganic": "අසෛව",
    "add.generateAi": "AI විස්තරය සාදන්න",
    "add.generatingAi": "AI අන්තර්ගතය සාදමින්...",
    "add.description": "විස්තරය",
    "add.benefits": "ලාභ (AI මඟින් පිරවෙයි)",
    "add.tags": "ටැග් (කොමා විසින් වෙන් කරන්න)",
    "add.retail": "සිල්ලර මිල",
    "add.wholesale": "තොග මිල",
    "add.minWholesale": "අවම තොග ප්‍රමාණය",
    "add.available": "ලබා ගත හැකි ප්‍රමාණය",
    "add.upload": "නිෂ්පාදන රූප උඩුගත කරන්න",
    "add.uploadHint": "විකල්පීයයි, උපරිම රූප 8ක් (එක් රූපයක් 5MB).",
    "add.noImage": "තවම රූපයක් තෝරා නැත.",
    "add.saving": "නිෂ්පාදනය සුරකිමින්...",
    "add.create": "නිෂ්පාදනය සාදන්න",

    "footer.description": "ශ්‍රී ලංකාව පුරා විශ්වාසදායී වෙළෙන්දන්ගෙන් නැවුම් නිෂ්පාදන සහ කෘෂි සැපයුම්.",
    "footer.marketplace": "වෙළඳපොළ",
    "footer.sell": "නිෂ්පාදන විකුණන්න",
    "footer.orders": "ඇණවුම්",
    "footer.cart": "කරත්තය",
    "footer.bottom": "ගොවිපල සිට වෙළඳපොළට හොඳ වෙළඳාමක් සඳහා.",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.products": "தயாரிப்புகள்",
    "nav.addProduct": "தயாரிப்பு சேர்க்க",
    "nav.cart": "வண்டி",
    "nav.orders": "ஆர்டர்கள்",
    "nav.admin": "நிர்வாகம்",
    "nav.logout": "வெளியேறு",
    "nav.login": "உள்நுழை",
    "nav.register": "பதிவு",
    "nav.language": "மொழி",
    "nav.toggleMenu": "மெனுவை மாற்று",

    "home.kicker": "விவசாய சந்தை",
    "home.headline": "புதிய காய்கறி, விதைகள் மற்றும் விவசாய பொருட்களை நேரடியாக விவசாயிகளிடமிருந்து வாங்குங்கள்.",
    "home.description": "நம்பகமான உள்ளூர் விற்பனையாளர்களுடன் தெளிவான பண்ணை-சந்தை வணிகத்திற்காக உருவாக்கப்பட்டது.",
    "home.explore": "சந்தையை பார்க்க",
    "home.becomeSeller": "விற்பனையாளர் ஆகுங்கள்",
    "home.categories": "பிரிவுகள்",
    "home.featured": "சிறப்பு தயாரிப்புகள்",
    "home.viewAll": "அனைத்தையும் காண்க",
    "home.noFeatured": "இன்னும் சிறப்பு தயாரிப்புகள் இல்லை.",
    "home.loadingFeatured": "சிறப்பு தயாரிப்புகள் ஏற்றப்படுகிறது...",

    "products.marketplace": "சந்தை",
    "products.category": "பிரிவு",
    "products.location": "இடம்",
    "products.organic": "இயற்கை",
    "products.minPrice": "குறைந்த விலை",
    "products.maxPrice": "அதிகபட்ச விலை",
    "products.all": "அனைத்தும்",
    "products.searchLocation": "இடம் தேடவும்",
    "products.nonOrganic": "இயற்கையல்லாத",
    "products.title": "தயாரிப்புகள்",
    "products.items": "{count} பொருட்கள்",
    "products.loading": "தயாரிப்புகள் ஏற்றப்படுகிறது...",
    "products.empty": "தேர்ந்தெடுத்த வடிகட்டலுக்கு தயாரிப்புகள் இல்லை.",

    "auth.loginTitle": "உள்நுழை",
    "auth.loginSubtitle": "உங்கள் வண்டி மற்றும் ஆர்டர்கள் அணுகவும்.",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.signingIn": "உள்நுழைகிறது...",
    "auth.newHere": "புதியவரா?",
    "auth.createAccount": "கணக்கு உருவாக்கவும்",
    "auth.registerTitle": "கணக்கு உருவாக்கவும்",
    "auth.registerSubtitle": "வாடிக்கையாளர், விவசாயி அல்லது விற்பனையாளர் ஆக பதிவு செய்யவும்.",
    "auth.name": "பெயர்",
    "auth.role": "பங்கு",
    "auth.customer": "வாடிக்கையாளர்",
    "auth.farmer": "விவசாயி",
    "auth.vendor": "விற்பனையாளர்",
    "auth.creating": "கணக்கு உருவாக்கப்படுகிறது...",
    "auth.register": "பதிவு",
    "auth.already": "ஏற்கனவே கணக்கு உள்ளதா?",

    "product.organic": "இயற்கை",
    "product.organicProduct": "இயற்கை தயாரிப்பு",
    "product.retail": "சில்லறை",
    "product.wholesale": "மொத்த",
    "product.addToCart": "வண்டியில் சேர்",
    "product.imageOf": "படம் {current} / {total}",
    "product.subcategory": "துணைப் பிரிவு",
    "product.minWholesale": "குறைந்தபட்ச மொத்த அளவு",
    "product.location": "இடம்",
    "product.availableQty": "கிடைக்கும் அளவு",
    "product.sellerDetails": "விற்பனையாளர் விவரங்கள்",
    "product.notFound": "தயாரிப்பு கிடைக்கவில்லை.",
    "product.loading": "தயாரிப்பு ஏற்றப்படுகிறது...",

    "common.na": "இல்லை",

    "cart.loading": "வண்டி ஏற்றப்படுகிறது...",
    "cart.title": "என் வண்டி",
    "cart.items": "{count} பொருட்கள்",
    "cart.empty": "உங்கள் வண்டி காலியாக உள்ளது.",
    "cart.remove": "நீக்கு",
    "cart.total": "மொத்தம்",
    "cart.checkout": "கட்டணம் செலுத்து",
    "cart.processing": "செயலாக்கம்...",

    "orders.loading": "ஆர்டர்கள் ஏற்றப்படுகிறது...",
    "orders.title": "என் ஆர்டர்கள்",
    "orders.count": "{count} ஆர்டர்கள்",
    "orders.none": "இன்னும் ஆர்டர்கள் இல்லை.",
    "orders.placed": "இட்ட தேதி",
    "orders.total": "மொத்தம்",
    "orders.order": "ஆர்டர்",

    "add.title": "தயாரிப்பு சேர்க்க",
    "add.productName": "தயாரிப்பு பெயர்",
    "add.category": "பிரிவு",
    "add.subcategory": "துணைப் பிரிவு",
    "add.location": "இடம்",
    "add.type": "வகை",
    "add.organic": "இயற்கை",
    "add.nonOrganic": "இயற்கையல்லாத",
    "add.generateAi": "AI விளக்கம் உருவாக்கு",
    "add.generatingAi": "AI உள்ளடக்கம் உருவாகிறது...",
    "add.description": "விளக்கம்",
    "add.benefits": "நன்மைகள் (AI தானாக நிரப்பும்)",
    "add.tags": "டாக்கள் (கமா மூலம் பிரிக்கவும்)",
    "add.retail": "சில்லறை விலை",
    "add.wholesale": "மொத்த விலை",
    "add.minWholesale": "குறைந்தபட்ச மொத்த அளவு",
    "add.available": "கிடைக்கும் அளவு",
    "add.upload": "தயாரிப்பு படங்களை பதிவேற்று",
    "add.uploadHint": "விருப்பம், அதிகபட்சம் 8 படங்கள் (ஒன்றுக்கு 5MB).",
    "add.noImage": "இன்னும் படம் தேர்ந்தெடுக்கப்படவில்லை.",
    "add.saving": "தயாரிப்பு சேமிக்கப்படுகிறது...",
    "add.create": "தயாரிப்பு உருவாக்கு",

    "footer.description": "இலங்கை முழுவதும் நம்பகமான விற்பனையாளர்களிடமிருந்து புதிய உற்பத்தி மற்றும் விவசாய பொருட்கள்.",
    "footer.marketplace": "சந்தை",
    "footer.sell": "தயாரிப்புகள் விற்பனை",
    "footer.orders": "ஆர்டர்கள்",
    "footer.cart": "வண்டி",
    "footer.bottom": "மேம்பட்ட பண்ணை-சந்தை வர்த்தகத்திற்காக.",
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const interpolate = (template, values = {}) =>
  String(template).replace(/\{(\w+)\}/g, (_match, token) =>
    values[token] !== undefined ? String(values[token]) : `{${token}}`
  );

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || "en");

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key, values) => {
      const current = TRANSLATIONS[language] || TRANSLATIONS.en;
      const fallback = TRANSLATIONS.en;
      const template = current[key] || fallback[key] || key;
      return interpolate(template, values);
    };

    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
