import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "app-language";

const TRANSLATIONS = {
  en: {
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.addProduct": "Add Product",
    "nav.cart": "Cart",
    "nav.orders": "Orders",
    "nav.admin": "Admin",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.language": "Language",
    "nav.toggleMenu": "Toggle menu",
    "nav.brandAlt": "Agri Market logo",

    "home.kicker": "Agriculture Marketplace",
    "home.headline": "Buy fresh produce, seeds, and agri supplies directly from farmers.",
    "home.description": "Built for transparent farm-to-market trade with trusted local sellers and efficient order management.",
    "home.explore": "Explore Marketplace",
    "home.becomeSeller": "Become a Seller",
    "home.categories": "Categories",
    "home.featured": "Featured Products",
    "home.viewAll": "View all",
    "home.noFeatured": "No featured products available yet.",
    "home.loadingFeatured": "Fetching featured products...",

    "products.marketplace": "Marketplace",
    "products.category": "Category",
    "products.location": "Location",
    "products.organic": "Organic",
    "products.minPrice": "Min Price",
    "products.maxPrice": "Max Price",
    "products.all": "All",
    "products.searchLocation": "Search location",
    "products.nonOrganic": "Non-organic",
    "products.title": "Products",
    "products.items": "{count} items",
    "products.loading": "Loading products...",
    "products.empty": "No products found for selected filters.",

    "category.Vegetables": "Vegetables",
    "category.Fruits": "Fruits",
    "category.Grains": "Grains",
    "category.Seeds": "Seeds",
    "category.Fertilizer": "Fertilizer",
    "category.Equipment": "Equipment",
    "category.Vehicles": "Vehicles",

    "auth.loginTitle": "Login",
    "auth.loginSubtitle": "Access your cart, orders, and purchase history.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signingIn": "Signing in...",
    "auth.newHere": "New here?",
    "auth.createAccount": "Create an account",
    "auth.registerTitle": "Create Account",
    "auth.registerSubtitle": "Register as customer, farmer, or vendor.",
    "auth.name": "Name",
    "auth.role": "Role",
    "auth.customer": "Customer",
    "auth.farmer": "Farmer",
    "auth.vendor": "Vendor",
    "auth.creating": "Creating account...",
    "auth.register": "Register",
    "auth.already": "Already have an account?",

    "product.organic": "Organic",
    "product.organicProduct": "Organic Product",
    "product.retail": "Retail",
    "product.wholesale": "Wholesale",
    "product.addToCart": "Add to Cart",
    "product.imageOf": "Image {current} of {total}",
    "product.subcategory": "Subcategory",
    "product.minWholesale": "Minimum wholesale qty",
    "product.location": "Location",
    "product.availableQty": "Available quantity",
    "product.sellerDetails": "Seller Details",
    "product.notFound": "Product not found.",
    "product.loading": "Loading product...",

    "common.na": "N/A",
    "common.checkingSession": "Checking session...",
    "common.checkingAccess": "Checking access...",

    "cart.loading": "Loading cart...",
    "cart.title": "My Cart",
    "cart.items": "{count} items",
    "cart.empty": "Your cart is empty.",
    "cart.remove": "Remove",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.processing": "Processing...",

    "orders.loading": "Loading orders...",
    "orders.title": "My Orders",
    "orders.count": "{count} orders",
    "orders.none": "No orders found yet.",
    "orders.placed": "Placed",
    "orders.total": "Total",
    "orders.order": "Order",

    "status.pending": "pending",
    "status.confirmed": "confirmed",
    "status.completed": "completed",
    "status.cancelled": "cancelled",

    "admin.panel": "Admin Panel",
    "admin.dashboard": "Dashboard",
    "admin.analytics": "Analytics",
    "admin.users": "Users",
    "admin.products": "Products",
    "admin.orders": "Orders",
    "admin.loadingDashboard": "Loading dashboard...",
    "admin.loadingUsers": "Loading users...",
    "admin.loadingProducts": "Loading products...",
    "admin.loadingOrders": "Loading orders...",
    "admin.loadingAnalytics": "Loading analytics...",
    "admin.analyticsFailed": "Failed to load analytics",
    "admin.refresh": "Refresh",
    "admin.platformReach": "Platform Reach",
    "admin.supplyNetwork": "Supply Network",
    "admin.marketplaceDepth": "Marketplace Depth",
    "admin.transactionFlow": "Transaction Flow",
    "admin.totalUsers": "Total Users",
    "admin.totalFarmers": "Total Farmers",
    "admin.totalFarmerVendors": "Total Farmers/Vendors",
    "admin.totalProducts": "Total Products",
    "admin.totalOrders": "Total Orders",
    "admin.totalRevenue": "Total Revenue",
    "admin.userManagement": "User Management",
    "admin.productManagement": "Product Management",
    "admin.orderManagement": "Order Management",
    "admin.usersCount": "{count} users",
    "admin.productsCount": "{count} products",
    "admin.ordersCount": "{count} orders",
    "admin.joined": "Joined",
    "admin.actions": "Actions",
    "admin.admin": "Admin",
    "admin.delete": "Delete",
    "admin.title": "Title",
    "admin.seller": "Seller",
    "admin.yes": "Yes",
    "admin.no": "No",
    "admin.orderId": "Order ID",
    "admin.buyer": "Buyer",
    "admin.status": "Status",
    "admin.date": "Date",
    "admin.items": "Items",
    "admin.salesByCategory": "Sales By Category",
    "admin.topProducts": "Top Products",
    "admin.topFarmers": "Top Farmers",
    "admin.locationDemand": "Location Demand",
    "admin.units": "units",

    "add.title": "Add Product",
    "add.productName": "Product Name",
    "add.category": "Category",
    "add.subcategory": "Subcategory",
    "add.location": "Location",
    "add.type": "Type",
    "add.organic": "Organic",
    "add.nonOrganic": "Non-organic",
    "add.generateAi": "Generate AI Description",
    "add.generatingAi": "Generating AI content...",
    "add.description": "Description",
    "add.benefits": "Benefits (auto-filled by AI)",
    "add.tags": "Tags (comma separated)",
    "add.retail": "Retail Price",
    "add.wholesale": "Wholesale Price",
    "add.minWholesale": "Min Wholesale Quantity",
    "add.available": "Available Quantity",
    "add.upload": "Upload Product Images",
    "add.uploadHint": "Optional, up to 8 images (max 5MB each).",
    "add.noImage": "No image selected yet.",
    "add.saving": "Saving Product...",
    "add.create": "Create Product",
    "add.tooManyImages": "You can upload up to 8 images only.",
    "add.aiNeedsBasics": "Please enter product name, category, and location before AI generation.",
    "add.aiGenerated": "AI content generated successfully.",
    "add.aiFailed": "Failed to generate AI content.",
    "add.createSuccess": "Product created successfully.",
    "add.createFailed": "Failed to create product.",

    "footer.description": "Fresh produce and agri supplies from trusted local sellers across Sri Lanka.",
    "footer.marketplace": "Marketplace",
    "footer.sell": "Sell Products",
    "footer.orders": "Orders",
    "footer.cart": "Cart",
    "footer.bottom": "Built for better farm-to-market trade.",
  },
  si: {
    "nav.home": "මුල් පිටුව",
    "nav.products": "නිෂ්පාදන",
    "nav.addProduct": "නිෂ්පාදනය එක් කරන්න",
    "nav.cart": "කරත්තය",
    "nav.orders": "ඇණවුම්",
    "nav.admin": "පරිපාලක",
    "nav.logout": "ඉවත් වන්න",
    "nav.login": "පිවිසුම",
    "nav.register": "ලියාපදිංචිය",
    "nav.language": "භාෂාව",
    "nav.toggleMenu": "මෙනුව විවෘත/වසා දමන්න",
    "nav.brandAlt": "Agri Market ලාංඡනය",

    "home.kicker": "කෘෂි වෙළඳපොළ",
    "home.headline": "නැවුම් අස්වැන්න, බීජ සහ කෘෂි සැපයුම් ගොවීන්ගෙන්ම මිලදී ගන්න.",
    "home.description": "විශ්වාසදායී වෙළෙන්දන් සමඟ පැහැදිලි ගොවිපල-වෙළඳපොළ වෙළඳාම සඳහා නිර්මාණය කර ඇත.",
    "home.explore": "වෙළඳපොළ බලන්න",
    "home.becomeSeller": "විකුණන්නා වන්න",
    "home.categories": "කාණ්ඩ",
    "home.featured": "ප්‍රධාන නිෂ්පාදන",
    "home.viewAll": "සියල්ල බලන්න",
    "home.noFeatured": "තවම ප්‍රධාන නිෂ්පාදන නොමැත.",
    "home.loadingFeatured": "ප්‍රධාන නිෂ්පාදන පූරණය වෙමින්...",

    "products.marketplace": "වෙළඳපොළ",
    "products.category": "කාණ්ඩය",
    "products.location": "ස්ථානය",
    "products.organic": "සෛව",
    "products.minPrice": "අවම මිල",
    "products.maxPrice": "උපරිම මිල",
    "products.all": "සියල්ල",
    "products.searchLocation": "ස්ථානය සොයන්න",
    "products.nonOrganic": "අසෛව",
    "products.title": "නිෂ්පාදන",
    "products.items": "අයිතම {count}",
    "products.loading": "නිෂ්පාදන පූරණය වෙමින්...",
    "products.empty": "තෝරාගත් පෙරහන් සඳහා නිෂ්පාදන නැත.",

    "category.Vegetables": "එළවළු",
    "category.Fruits": "පළතුරු",
    "category.Grains": "ධාන්‍ය",
    "category.Seeds": "බීජ",
    "category.Fertilizer": "පොහොර",
    "category.Equipment": "උපකරණ",
    "category.Vehicles": "වාහන",

    "auth.loginTitle": "පිවිසුම",
    "auth.loginSubtitle": "ඔබගේ කරත්තය සහ ඇණවුම් වෙත ප්‍රවේශ වන්න.",
    "auth.email": "ඊමේල්",
    "auth.password": "මුරපදය",
    "auth.signingIn": "පිවිසෙමින්...",
    "auth.newHere": "අලුත්ද?",
    "auth.createAccount": "ගිණුමක් සාදන්න",
    "auth.registerTitle": "ගිණුම සාදන්න",
    "auth.registerSubtitle": "පාරිභෝගික, ගොවි හෝ වෙළෙන්දා ලෙස ලියාපදිංචි වන්න.",
    "auth.name": "නම",
    "auth.role": "භූමිකාව",
    "auth.customer": "පාරිභෝගික",
    "auth.farmer": "ගොවි",
    "auth.vendor": "වෙළෙන්දා",
    "auth.creating": "ගිණුම සාදමින්...",
    "auth.register": "ලියාපදිංචි වන්න",
    "auth.already": "දැනටමත් ගිණුමක් තිබේද?",

    "product.organic": "සෛව",
    "product.organicProduct": "සෛව නිෂ්පාදනය",
    "product.retail": "සිල්ලර",
    "product.wholesale": "තොග",
    "product.addToCart": "කරත්තයට එක් කරන්න",
    "product.imageOf": "රූපය {current} / {total}",
    "product.subcategory": "උප කාණ්ඩය",
    "product.minWholesale": "අවම තොග ප්‍රමාණය",
    "product.location": "ස්ථානය",
    "product.availableQty": "ලබා ගත හැකි ප්‍රමාණය",
    "product.sellerDetails": "විකුණන්නාගේ තොරතුරු",
    "product.notFound": "නිෂ්පාදනය හමු නොවීය.",
    "product.loading": "නිෂ්පාදනය පූරණය වෙමින්...",

    "common.na": "නැත",
    "common.checkingSession": "සැසිය පරීක්ෂා වෙමින්...",
    "common.checkingAccess": "ප්‍රවේශය පරීක්ෂා වෙමින්...",

    "cart.loading": "කරත්තය පූරණය වෙමින්...",
    "cart.title": "මගේ කරත්තය",
    "cart.items": "අයිතම {count}",
    "cart.empty": "ඔබගේ කරත්තය හිස්ය.",
    "cart.remove": "ඉවත් කරන්න",
    "cart.total": "එකතුව",
    "cart.checkout": "ගෙවීමට යන්න",
    "cart.processing": "සැකසෙමින්...",

    "orders.loading": "ඇණවුම් පූරණය වෙමින්...",
    "orders.title": "මගේ ඇණවුම්",
    "orders.count": "ඇණවුම් {count}",
    "orders.none": "තවම ඇණවුම් නොමැත.",
    "orders.placed": "තැබූ දිනය",
    "orders.total": "එකතුව",
    "orders.order": "ඇණවුම",

    "status.pending": "පොරොත්තුවේ",
    "status.confirmed": "තහවුරු කළ",
    "status.completed": "සම්පූර්ණ",
    "status.cancelled": "අවලංගු",

    "admin.panel": "පරිපාලක පුවරුව",
    "admin.dashboard": "ඩෑෂ්බෝර්ඩ්",
    "admin.analytics": "විශ්ලේෂණ",
    "admin.users": "පරිශීලකයින්",
    "admin.products": "නිෂ්පාදන",
    "admin.orders": "ඇණවුම්",
    "admin.loadingDashboard": "ඩෑෂ්බෝර්ඩ් පූරණය වෙමින්...",
    "admin.loadingUsers": "පරිශීලකයින් පූරණය වෙමින්...",
    "admin.loadingProducts": "නිෂ්පාදන පූරණය වෙමින්...",
    "admin.loadingOrders": "ඇණවුම් පූරණය වෙමින්...",
    "admin.loadingAnalytics": "විශ්ලේෂණ පූරණය වෙමින්...",
    "admin.analyticsFailed": "විශ්ලේෂණ පූරණය කිරීමට අසමත් විය",
    "admin.refresh": "නැවත පූරණය",
    "admin.platformReach": "වේදිකා ප්‍රාප්තිය",
    "admin.supplyNetwork": "සැපයුම් ජාලය",
    "admin.marketplaceDepth": "වෙළඳපොළ ගැඹුර",
    "admin.transactionFlow": "ගනුදෙනු ප්‍රවාහය",
    "admin.totalUsers": "මුළු පරිශීලකයින්",
    "admin.totalFarmers": "මුළු ගොවීන්",
    "admin.totalFarmerVendors": "මුළු ගොවි/වෙළෙන්දෝ",
    "admin.totalProducts": "මුළු නිෂ්පාදන",
    "admin.totalOrders": "මුළු ඇණවුම්",
    "admin.totalRevenue": "මුළු ආදායම",
    "admin.userManagement": "පරිශීලක කළමනාකරණය",
    "admin.productManagement": "නිෂ්පාදන කළමනාකරණය",
    "admin.orderManagement": "ඇණවුම් කළමනාකරණය",
    "admin.usersCount": "පරිශීලකයින් {count}",
    "admin.productsCount": "නිෂ්පාදන {count}",
    "admin.ordersCount": "ඇණවුම් {count}",
    "admin.joined": "එකතු වූ දිනය",
    "admin.actions": "ක්‍රියා",
    "admin.admin": "පරිපාලක",
    "admin.delete": "මකන්න",
    "admin.title": "ශීර්ෂය",
    "admin.seller": "විකුණන්නා",
    "admin.yes": "ඔව්",
    "admin.no": "නැත",
    "admin.orderId": "ඇණවුම් අංකය",
    "admin.buyer": "ගැනුම්කරු",
    "admin.status": "තත්වය",
    "admin.date": "දිනය",
    "admin.items": "අයිතම",
    "admin.salesByCategory": "කාණ්ඩ අනුව විකුණුම්",
    "admin.topProducts": "ඉහළ නිෂ්පාදන",
    "admin.topFarmers": "ඉහළ ගොවීන්",
    "admin.locationDemand": "ප්‍රදේශික ඉල්ලුම",
    "admin.units": "ඒකක",

    "add.title": "නිෂ්පාදනය එක් කරන්න",
    "add.productName": "නිෂ්පාදන නම",
    "add.category": "කාණ්ඩය",
    "add.subcategory": "උප කාණ්ඩය",
    "add.location": "ස්ථානය",
    "add.type": "වර්ගය",
    "add.organic": "සෛව",
    "add.nonOrganic": "අසෛව",
    "add.generateAi": "AI විස්තරය සාදන්න",
    "add.generatingAi": "AI අන්තර්ගතය සාදමින්...",
    "add.description": "විස්තරය",
    "add.benefits": "ලාභ (AI මඟින් පිරවෙයි)",
    "add.tags": "ටැග් (කොමා විසින් වෙන් කරන්න)",
    "add.retail": "සිල්ලර මිල",
    "add.wholesale": "තොග මිල",
    "add.minWholesale": "අවම තොග ප්‍රමාණය",
    "add.available": "ලබා ගත හැකි ප්‍රමාණය",
    "add.upload": "නිෂ්පාදන රූප උඩුගත කරන්න",
    "add.uploadHint": "විකල්පීයයි, උපරිම රූප 8ක් (එක් රූපයක් 5MB).",
    "add.noImage": "තවම රූපයක් තෝරා නැත.",
    "add.saving": "නිෂ්පාදනය සුරකිමින්...",
    "add.create": "නිෂ්පාදනය සාදන්න",
    "add.tooManyImages": "ඔබට රූප 8ක් දක්වා පමණක් උඩුගත කළ හැක.",
    "add.aiNeedsBasics": "AI ජනනයට පෙර නිෂ්පාදන නම, කාණ්ඩය සහ ස්ථානය ඇතුළත් කරන්න.",
    "add.aiGenerated": "AI අන්තර්ගතය සාර්ථකව ජනනය කරන ලදී.",
    "add.aiFailed": "AI අන්තර්ගතය ජනනය කිරීමට අසමත් විය.",
    "add.createSuccess": "නිෂ්පාදනය සාර්ථකව සාදන ලදී.",
    "add.createFailed": "නිෂ්පාදනය සෑදීමට අසමත් විය.",

    "footer.description": "ශ්‍රී ලංකාව පුරා විශ්වාසදායී වෙළෙන්දන්ගෙන් නැවුම් නිෂ්පාදන සහ කෘෂි සැපයුම්.",
    "footer.marketplace": "වෙළඳපොළ",
    "footer.sell": "නිෂ්පාදන විකුණන්න",
    "footer.orders": "ඇණවුම්",
    "footer.cart": "කරත්තය",
    "footer.bottom": "ගොවිපල සිට වෙළඳපොළට හොඳ වෙළඳාමක් සඳහා.",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.products": "தயாரிப்புகள்",
    "nav.addProduct": "தயாரிப்பு சேர்க்க",
    "nav.cart": "வண்டி",
    "nav.orders": "ஆர்டர்கள்",
    "nav.admin": "நிர்வாகம்",
    "nav.logout": "வெளியேறு",
    "nav.login": "உள்நுழை",
    "nav.register": "பதிவு",
    "nav.language": "மொழி",
    "nav.toggleMenu": "மெனுவை மாற்று",
    "nav.brandAlt": "Agri Market சின்னம்",

    "home.kicker": "விவசாய சந்தை",
    "home.headline": "புதிய காய்கறி, விதைகள் மற்றும் விவசாய பொருட்களை நேரடியாக விவசாயிகளிடமிருந்து வாங்குங்கள்.",
    "home.description": "நம்பகமான உள்ளூர் விற்பனையாளர்களுடன் தெளிவான பண்ணை-சந்தை வணிகத்திற்காக உருவாக்கப்பட்டது.",
    "home.explore": "சந்தையை பார்க்க",
    "home.becomeSeller": "விற்பனையாளர் ஆகுங்கள்",
    "home.categories": "பிரிவுகள்",
    "home.featured": "சிறப்பு தயாரிப்புகள்",
    "home.viewAll": "அனைத்தையும் காண்க",
    "home.noFeatured": "இன்னும் சிறப்பு தயாரிப்புகள் இல்லை.",
    "home.loadingFeatured": "சிறப்பு தயாரிப்புகள் ஏற்றப்படுகிறது...",

    "products.marketplace": "சந்தை",
    "products.category": "பிரிவு",
    "products.location": "இடம்",
    "products.organic": "இயற்கை",
    "products.minPrice": "குறைந்த விலை",
    "products.maxPrice": "அதிகபட்ச விலை",
    "products.all": "அனைத்தும்",
    "products.searchLocation": "இடம் தேடவும்",
    "products.nonOrganic": "இயற்கையல்லாத",
    "products.title": "தயாரிப்புகள்",
    "products.items": "{count} பொருட்கள்",
    "products.loading": "தயாரிப்புகள் ஏற்றப்படுகிறது...",
    "products.empty": "தேர்ந்தெடுத்த வடிகட்டலுக்கு தயாரிப்புகள் இல்லை.",

    "category.Vegetables": "காய்கறிகள்",
    "category.Fruits": "பழங்கள்",
    "category.Grains": "தானியங்கள்",
    "category.Seeds": "விதைகள்",
    "category.Fertilizer": "உரம்",
    "category.Equipment": "உபகரணங்கள்",
    "category.Vehicles": "வாகனங்கள்",

    "auth.loginTitle": "உள்நுழை",
    "auth.loginSubtitle": "உங்கள் வண்டி மற்றும் ஆர்டர்கள் அணுகவும்.",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.signingIn": "உள்நுழைகிறது...",
    "auth.newHere": "புதியவரா?",
    "auth.createAccount": "கணக்கு உருவாக்கவும்",
    "auth.registerTitle": "கணக்கு உருவாக்கவும்",
    "auth.registerSubtitle": "வாடிக்கையாளர், விவசாயி அல்லது விற்பனையாளர் ஆக பதிவு செய்யவும்.",
    "auth.name": "பெயர்",
    "auth.role": "பங்கு",
    "auth.customer": "வாடிக்கையாளர்",
    "auth.farmer": "விவசாயி",
    "auth.vendor": "விற்பனையாளர்",
    "auth.creating": "கணக்கு உருவாக்கப்படுகிறது...",
    "auth.register": "பதிவு",
    "auth.already": "ஏற்கனவே கணக்கு உள்ளதா?",

    "product.organic": "இயற்கை",
    "product.organicProduct": "இயற்கை தயாரிப்பு",
    "product.retail": "சில்லறை",
    "product.wholesale": "மொத்த",
    "product.addToCart": "வண்டியில் சேர்",
    "product.imageOf": "படம் {current} / {total}",
    "product.subcategory": "துணைப் பிரிவு",
    "product.minWholesale": "குறைந்தபட்ச மொத்த அளவு",
    "product.location": "இடம்",
    "product.availableQty": "கிடைக்கும் அளவு",
    "product.sellerDetails": "விற்பனையாளர் விவரங்கள்",
    "product.notFound": "தயாரிப்பு கிடைக்கவில்லை.",
    "product.loading": "தயாரிப்பு ஏற்றப்படுகிறது...",

    "common.na": "இல்லை",
    "common.checkingSession": "அமர்வு சரிபார்க்கப்படுகிறது...",
    "common.checkingAccess": "அணுகல் சரிபார்க்கப்படுகிறது...",

    "cart.loading": "வண்டி ஏற்றப்படுகிறது...",
    "cart.title": "என் வண்டி",
    "cart.items": "{count} பொருட்கள்",
    "cart.empty": "உங்கள் வண்டி காலியாக உள்ளது.",
    "cart.remove": "நீக்கு",
    "cart.total": "மொத்தம்",
    "cart.checkout": "கட்டணம் செலுத்து",
    "cart.processing": "செயலாக்கம்...",

    "orders.loading": "ஆர்டர்கள் ஏற்றப்படுகிறது...",
    "orders.title": "என் ஆர்டர்கள்",
    "orders.count": "{count} ஆர்டர்கள்",
    "orders.none": "இன்னும் ஆர்டர்கள் இல்லை.",
    "orders.placed": "இட்ட தேதி",
    "orders.total": "மொத்தம்",
    "orders.order": "ஆர்டர்",

    "status.pending": "நிலுவையில்",
    "status.confirmed": "உறுதிப்படுத்தப்பட்டது",
    "status.completed": "முடிந்தது",
    "status.cancelled": "ரத்து செய்யப்பட்டது",

    "admin.panel": "நிர்வாக பலகம்",
    "admin.dashboard": "டாஷ்போர்டு",
    "admin.analytics": "பகுப்பாய்வு",
    "admin.users": "பயனர்கள்",
    "admin.products": "தயாரிப்புகள்",
    "admin.orders": "ஆர்டர்கள்",
    "admin.loadingDashboard": "டாஷ்போர்டு ஏற்றப்படுகிறது...",
    "admin.loadingUsers": "பயனர்கள் ஏற்றப்படுகிறது...",
    "admin.loadingProducts": "தயாரிப்புகள் ஏற்றப்படுகிறது...",
    "admin.loadingOrders": "ஆர்டர்கள் ஏற்றப்படுகிறது...",
    "admin.loadingAnalytics": "பகுப்பாய்வு ஏற்றப்படுகிறது...",
    "admin.analyticsFailed": "பகுப்பாய்வு ஏற்ற முடியவில்லை",
    "admin.refresh": "புதுப்பிப்பு",
    "admin.platformReach": "தள விரிவடைவு",
    "admin.supplyNetwork": "வழங்கல் வலைப்பின்னல்",
    "admin.marketplaceDepth": "சந்தை ஆழம்",
    "admin.transactionFlow": "பரிவர்த்தனை ஓட்டம்",
    "admin.totalUsers": "மொத்த பயனர்கள்",
    "admin.totalFarmers": "மொத்த விவசாயிகள்",
    "admin.totalFarmerVendors": "மொத்த விவசாயி/விற்பனையாளர்கள்",
    "admin.totalProducts": "மொத்த தயாரிப்புகள்",
    "admin.totalOrders": "மொத்த ஆர்டர்கள்",
    "admin.totalRevenue": "மொத்த வருவாய்",
    "admin.userManagement": "பயனர் மேலாண்மை",
    "admin.productManagement": "தயாரிப்பு மேலாண்மை",
    "admin.orderManagement": "ஆர்டர் மேலாண்மை",
    "admin.usersCount": "{count} பயனர்கள்",
    "admin.productsCount": "{count} தயாரிப்புகள்",
    "admin.ordersCount": "{count} ஆர்டர்கள்",
    "admin.joined": "சேர்ந்த தேதி",
    "admin.actions": "செயல்கள்",
    "admin.admin": "நிர்வாகம்",
    "admin.delete": "நீக்கு",
    "admin.title": "தலைப்பு",
    "admin.seller": "விற்பனையாளர்",
    "admin.yes": "ஆம்",
    "admin.no": "இல்லை",
    "admin.orderId": "ஆர்டர் ஐடி",
    "admin.buyer": "வாங்குபவர்",
    "admin.status": "நிலை",
    "admin.date": "தேதி",
    "admin.items": "பொருட்கள்",
    "admin.salesByCategory": "பிரிவு வாரியான விற்பனை",
    "admin.topProducts": "முன்னணி தயாரிப்புகள்",
    "admin.topFarmers": "முன்னணி விவசாயிகள்",
    "admin.locationDemand": "பகுதி தேவை",
    "admin.units": "அலகுகள்",

    "add.title": "தயாரிப்பு சேர்க்க",
    "add.productName": "தயாரிப்பு பெயர்",
    "add.category": "பிரிவு",
    "add.subcategory": "துணைப் பிரிவு",
    "add.location": "இடம்",
    "add.type": "வகை",
    "add.organic": "இயற்கை",
    "add.nonOrganic": "இயற்கையல்லாத",
    "add.generateAi": "AI விளக்கம் உருவாக்கு",
    "add.generatingAi": "AI உள்ளடக்கம் உருவாகிறது...",
    "add.description": "விளக்கம்",
    "add.benefits": "நன்மைகள் (AI தானாக நிரப்பும்)",
    "add.tags": "டாக்கள் (கமா மூலம் பிரிக்கவும்)",
    "add.retail": "சில்லறை விலை",
    "add.wholesale": "மொத்த விலை",
    "add.minWholesale": "குறைந்தபட்ச மொத்த அளவு",
    "add.available": "கிடைக்கும் அளவு",
    "add.upload": "தயாரிப்பு படங்களை பதிவேற்று",
    "add.uploadHint": "விருப்பம், அதிகபட்சம் 8 படங்கள் (ஒன்றுக்கு 5MB).",
    "add.noImage": "இன்னும் படம் தேர்ந்தெடுக்கப்படவில்லை.",
    "add.saving": "தயாரிப்பு சேமிக்கப்படுகிறது...",
    "add.create": "தயாரிப்பு உருவாக்கு",
    "add.tooManyImages": "அதிகபட்சம் 8 படங்கள் மட்டுமே பதிவேற்றலாம்.",
    "add.aiNeedsBasics": "AI உருவாக்கத்திற்கு முன் தயாரிப்பு பெயர், பிரிவு, இடம் உள்ளிடவும்.",
    "add.aiGenerated": "AI உள்ளடக்கம் வெற்றிகரமாக உருவாக்கப்பட்டது.",
    "add.aiFailed": "AI உள்ளடக்கம் உருவாக்க முடியவில்லை.",
    "add.createSuccess": "தயாரிப்பு வெற்றிகரமாக உருவாக்கப்பட்டது.",
    "add.createFailed": "தயாரிப்பு உருவாக்க முடியவில்லை.",

    "footer.description": "இலங்கை முழுவதும் நம்பகமான விற்பனையாளர்களிடமிருந்து புதிய உற்பத்தி மற்றும் விவசாய பொருட்கள்.",
    "footer.marketplace": "சந்தை",
    "footer.sell": "தயாரிப்புகள் விற்பனை",
    "footer.orders": "ஆர்டர்கள்",
    "footer.cart": "வண்டி",
    "footer.bottom": "மேம்பட்ட பண்ணை-சந்தை வர்த்தகத்திற்காக.",
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const interpolate = (template, values = {}) =>
  String(template).replace(/\{(\w+)\}/g, (_match, token) =>
    values[token] !== undefined ? String(values[token]) : `{${token}}`
  );

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || "en");

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key, values) => {
      const current = TRANSLATIONS[language] || TRANSLATIONS.en;
      const fallback = TRANSLATIONS.en;
      const template = current[key] || fallback[key] || key;
      return interpolate(template, values);
    };

    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
